
[project]
name = "break-away" 
version = "0.1"
description = "A simple brick breaker game"
authors = [
    {name = "Shawn Dunn" , email = "sdunn15@my.wctc.edu"}
]

maintainers = [
    {name = "Shawn Dunn" , email = "sdunn15@my.wctc.edu"}
]